language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v2.1.1/git-lfs-linux-amd64-2.1.1.tar.gz
  - tar xvfz git-lfs-linux-amd64-2.1.1.tar.gz
  - mv git-lfs-2.1.1/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/

install:
  - python setup.py develop
  - pip install -e .[test]
  - pip install -U pytest

before_script:
  - git lfs pull
script:
  - flake8 gmalthgtparser
  - pytest -v gmalthgtparser/test/
